"""Make chunk_embeddings.vector a real pgvector column (replaces the JSON placeholder).

The extension is created idempotently so a fresh install needs no manual step. The tracer-bullet
embeddings stored as JSON are not durable (they are regenerated by re-indexing), so the column is
dropped and re-added as `vector` rather than cast in place.

Revision ID: 0004_pgvector_embeddings
Revises: 0003_chunk_embeddings
Create Date: 2026-10-05 15:00:00+07:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0004_pgvector_embeddings"
down_revision: str | Sequence[str] | None = "0003_chunk_embeddings"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Old JSON embeddings are not durable; clearing them lets the NOT NULL vector column be added cleanly.
    op.execute("TRUNCATE TABLE chunk_embeddings")
    op.drop_column("chunk_embeddings", "vector")
    op.add_column("chunk_embeddings", sa.Column("vector", Vector(), nullable=False))


def downgrade() -> None:
    op.drop_column("chunk_embeddings", "vector")
    op.add_column("chunk_embeddings", sa.Column("vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
