"""Turn wizard answers into deploy/compose/.env, seaweedfs/s3.json and e2eai.yaml."""

import json
import os
import re
import secrets
import time
from pathlib import Path

import yaml

from .services import BY_NAME, SECRETS, SERVICES, USERS, enabled_services

# URL-unreserved characters only: safe inside DSNs, .env files and SQL without escaping.
_SAFE = re.compile(r"^[A-Za-z0-9._~-]+$")
MIN_SECRET_LEN = 16

REQUIRED_ENV_KEYS = (
    ["COMPOSE_PROJECT_NAME", "COMPOSE_PROFILES", "COMPOSE_FILE", "COMPOSE_PATH_SEPARATOR", "BIND_ADDRESS",
     "OLLAMA_BASE_URL", "TEI_EMBED_MODEL", "TEI_RERANK_MODEL"]
    + [s.port_env for s in SERVICES] + list(USERS) + list(SECRETS)
)


def new_secret(prefix: str = "") -> str:
    return prefix + secrets.token_urlsafe(24)


def validate_secret(value: str) -> str | None:
    if len(value) < MIN_SECRET_LEN:
        return f"must be at least {MIN_SECRET_LEN} characters"
    if not _SAFE.match(value):
        return "use only letters, digits and . _ ~ -"
    return None


def validate_username(value: str) -> str | None:
    return None if re.fullmatch(r"[a-z][a-z0-9_-]{2,31}", value) else "3-32 chars: lowercase letters, digits, _ or -, starting with a letter"


def default_answers(tier: str, ports: dict[str, int], host_ollama: bool, gpu: bool) -> dict:
    return {
        "tier": tier,
        "bind": "127.0.0.1",
        "gpu": gpu,
        "host_ollama": host_ollama,
        "optional": {"ollama": not host_ollama, "tei-embed": False, "tei-rerank": False, "keycloak": tier != "lite"},
        "tei_models": {"tei-embed": "", "tei-rerank": ""},
        "ports": dict(ports),
        "users": {k: default or "e2eai-" + secrets.token_hex(4) for k, (_, _, default) in USERS.items()},
        "secrets": {k: new_secret(prefix) for k, (_, _, prefix) in SECRETS.items()},
    }


def _port(a: dict, name: str) -> int:
    return a["ports"].get(name, BY_NAME[name].default_port)


def render_env(a: dict, images: dict[str, str]) -> str:
    enabled = enabled_services(a)
    profiles = [BY_NAME[n].profile for n in enabled if BY_NAME[n].profile]
    files = ["compose.yaml"] + (["compose.gpu.yaml"] if a["gpu"] and "ollama" in enabled else [])
    lines = [
        "# Generated by the e2eai wizard. Contains secrets: never commit, never share.",
        "COMPOSE_PROJECT_NAME=e2eai",
        f"COMPOSE_PROFILES={','.join(profiles)}",
        "COMPOSE_PATH_SEPARATOR=,",
        f"COMPOSE_FILE={','.join(files)}",
        f"BIND_ADDRESS={a['bind']}",
        "OLLAMA_BASE_URL=" + ("http://host.docker.internal:11434" if a["host_ollama"] else "http://ollama:11434"),
        f"TEI_EMBED_MODEL={a['tei_models']['tei-embed']}",
        f"TEI_RERANK_MODEL={a['tei_models']['tei-rerank']}",
        "",
        "# Images (from deploy/versions.lock)",
        *(f"E2EAI_IMAGE_{k.upper()}={v}" for k, v in images.items()),
        "",
        "# Host ports",
        *(f"{s.port_env}={_port(a, s.name)}" for s in SERVICES),
        "",
        "# Usernames",
        *(f"{k}={v}" for k, v in a["users"].items()),
        "",
        "# Secrets",
        *(f"{k}={v}" for k, v in a["secrets"].items()),
    ]
    return "\n".join(lines) + "\n"


def render_s3_config(a: dict) -> str:
    identity = {
        "name": "e2eai",
        "credentials": [{"accessKey": a["users"]["S3_ACCESS_KEY"], "secretKey": a["secrets"]["S3_SECRET_KEY"]}],
        "actions": ["Admin", "Read", "Write", "List", "Tagging"],
    }
    return json.dumps({"identities": [identity]}, indent=2) + "\n"


def render_config(a: dict) -> str:
    enabled = enabled_services(a)
    cfg = {
        "tier": a["tier"],
        "components": {
            "auth": "oidc" if "keycloak" in enabled else "local",
            "job_engine": "celery",  # Temporal arrives in Phase 2 (FR-F20, P1)
            "vector_store": "pgvector",
            "tracing": "postgres",
        },
        "network": {"bind_address": a["bind"]},
        "services": {n: {"port": _port(a, n)} for n in enabled},
        "ollama": {"mode": "host" if a["host_ollama"] else "container", "gpu": a["gpu"]},
        "models": {  # chat/vision models are chosen in the model step (FR-F5a); none are shipped
            "chat": [],
            "embedding": [m for m in [a["tei_models"]["tei-embed"]] if m],
            "reranker": [m for m in [a["tei_models"]["tei-rerank"]] if m],
            "vision": [],
        },
        "egress": {"external_apis": False},
        "secrets": {k.lower(): f"env:{k}" for k in a["secrets"]},
    }
    header = "# Generated by the e2eai wizard (FR-F21). No secrets here: they live in deploy/compose/.env.\n"
    return header + yaml.safe_dump(cfg, sort_keys=False)


def _write_private(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    os.chmod(path, 0o600)  # owner-only on POSIX; best effort on Windows


def write_all(root: Path, a: dict, force: bool) -> list[Path]:
    compose = root / "deploy" / "compose"
    env = compose / ".env"
    if env.exists():
        if not force:
            raise FileExistsError(env)
        env.rename(compose / f".env.bak-{time.strftime('%Y%m%d-%H%M%S')}")
    images = yaml.safe_load((root / "deploy" / "versions.lock").read_text())["images"]
    _write_private(env, render_env(a, images))
    _write_private(compose / "seaweedfs" / "s3.json", render_s3_config(a))
    (root / "e2eai.yaml").write_text(render_config(a), encoding="utf-8", newline="\n")
    return [env, compose / "seaweedfs" / "s3.json", root / "e2eai.yaml"]
