"""Turn wizard answers into deploy/compose/.env, seaweedfs/s3.json and e2eai.yaml."""

import json
import os
import re
import secrets
import time
from pathlib import Path

import yaml

from .models import EXTERNAL_PROVIDERS, ROLES, Model, load_catalog
from .services import BY_NAME, SECRETS, SERVICES, USERS, enabled_services

# URL-unreserved characters only: safe inside DSNs, .env files and SQL without escaping.
_SAFE = re.compile(r"^[A-Za-z0-9._~-]+$")
MIN_SECRET_LEN = 16

REQUIRED_ENV_KEYS = (
    ["COMPOSE_PROJECT_NAME", "COMPOSE_PROFILES", "COMPOSE_FILE", "COMPOSE_PATH_SEPARATOR", "BIND_ADDRESS",
     "OLLAMA_BASE_URL", "TEI_EMBED_MODEL", "TEI_RERANK_MODEL"]
    + [s.port_env for s in SERVICES] + list(USERS) + list(SECRETS)
)


def new_secret(prefix: str = "") -> str:
    return prefix + secrets.token_urlsafe(24)


def validate_secret(value: str) -> str | None:
    if len(value) < MIN_SECRET_LEN:
        return f"must be at least {MIN_SECRET_LEN} characters"
    if not _SAFE.match(value):
        return "use only letters, digits and . _ ~ -"
    return None


def validate_username(value: str) -> str | None:
    return None if re.fullmatch(r"[a-z][a-z0-9_-]{2,31}", value) else "3-32 chars: lowercase letters, digits, _ or -, starting with a letter"


def default_answers(tier: str, ports: dict[str, int], host_ollama: bool, gpu: bool) -> dict:
    return {
        "tier": tier,
        "bind": "127.0.0.1",
        "gpu": gpu,
        "host_ollama": host_ollama,
        "optional": {"ollama": not host_ollama, "tei-embed": False, "tei-rerank": False, "keycloak": tier != "lite"},
        "tei_models": {"tei-embed": "", "tei-rerank": ""},
        "ports": dict(ports),
        "users": {k: default or "e2eai-" + secrets.token_hex(4) for k, (_, _, default) in USERS.items()},
        "secrets": {k: new_secret(prefix) for k, (_, _, prefix) in SECRETS.items()},
        "models": {r: [] for r in ROLES} | {"external": []},
        "api_keys": {},
        "egress_external": False,
    }


def _port(a: dict, name: str) -> int:
    return a["ports"].get(name, BY_NAME[name].default_port)


def render_env(a: dict, images: dict[str, str]) -> str:
    enabled = enabled_services(a)
    profiles = [BY_NAME[n].profile for n in enabled if BY_NAME[n].profile]
    files = ["compose.yaml"] + (["compose.gpu.yaml"] if a["gpu"] and "ollama" in enabled else [])
    lines = [
        "# Generated by the e2eai wizard. Contains secrets: never commit, never share.",
        "COMPOSE_PROJECT_NAME=e2eai",
        f"COMPOSE_PROFILES={','.join(profiles)}",
        "COMPOSE_PATH_SEPARATOR=,",
        f"COMPOSE_FILE={','.join(files)}",
        f"BIND_ADDRESS={a['bind']}",
        "OLLAMA_BASE_URL=" + ("http://host.docker.internal:11434" if a["host_ollama"] else "http://ollama:11434"),
        f"TEI_EMBED_MODEL={a['tei_models']['tei-embed']}",
        f"TEI_RERANK_MODEL={a['tei_models']['tei-rerank']}",
        "",
        "# Images (from deploy/versions.lock)",
        *(f"E2EAI_IMAGE_{k.upper()}={v}" for k, v in images.items()),
        "",
        "# Host ports",
        *(f"{s.port_env}={_port(a, s.name)}" for s in SERVICES),
        "",
        "# Usernames",
        *(f"{k}={v}" for k, v in a["users"].items()),
        "",
        "# Secrets",
        *(f"{k}={v}" for k, v in a["secrets"].items()),
        "",
        "# External model API keys (only when external APIs are enabled, FR-M9)",
        *(f"{k}={v}" for k, v in a["api_keys"].items()),
    ]
    return "\n".join(lines) + "\n"


def render_s3_config(a: dict) -> str:
    identity = {
        "name": "e2eai",
        "credentials": [{"accessKey": a["users"]["S3_ACCESS_KEY"], "secretKey": a["secrets"]["S3_SECRET_KEY"]}],
        "actions": ["Admin", "Read", "Write", "List", "Tagging"],
    }
    return json.dumps({"identities": [identity]}, indent=2) + "\n"


def render_config(a: dict) -> str:
    enabled = enabled_services(a)
    cfg = {
        "tier": a["tier"],
        "components": {
            "auth": "oidc" if "keycloak" in enabled else "local",
            "job_engine": "celery",  # Temporal arrives in Phase 2 (FR-F20, P1)
            "vector_store": "pgvector",
            "tracing": "postgres",
        },
        "network": {"bind_address": a["bind"]},
        "services": {n: {"port": _port(a, n)} for n in enabled},
        "ollama": {"mode": "host" if a["host_ollama"] else "container", "gpu": a["gpu"]},
        "models": a["models"],  # chosen in the model step (FR-F5a); none are shipped
        "egress": {"external_apis": a["egress_external"]},
        "secrets": {k.lower(): f"env:{k}" for k in a["secrets"]},
    }
    header = "# Generated by the e2eai wizard (FR-F21). No secrets here: they live in deploy/compose/.env.\n"
    return header + yaml.safe_dump(cfg, sort_keys=False)


def render_litellm_config(a: dict, catalog: dict[str, Model]) -> str:
    """Gateway routes for every chosen model. Keys are referenced (os.environ/...), never written here."""
    entries = []
    for role in ROLES:
        if role == "reranker":
            continue  # rerankers are called on TEI directly (PRD T2)
        for model_id in a["models"][role]:
            m = catalog[model_id]
            if m.served_by == "ollama":
                prefix = "ollama" if role == "embedding" else "ollama_chat"
                params = {"model": f"{prefix}/{m.source}", "api_base": "os.environ/OLLAMA_BASE_URL"}
            else:  # TEI exposes an OpenAI-compatible /v1/embeddings
                params = {"model": f"openai/{m.source}", "api_base": "http://tei-embed:80/v1", "api_key": "os.environ/TEI_API_KEY"}
            entry = {"model_name": m.id, "litellm_params": params}
            if role == "embedding":
                entry["model_info"] = {"mode": "embedding"}
            entries.append(entry)
    for ext in a["models"]["external"]:
        prefix, key_env = EXTERNAL_PROVIDERS[ext["provider"]]
        name = f"{prefix}/{ext['model']}"
        entries.append({"model_name": name, "litellm_params": {"model": name, "api_key": f"os.environ/{key_env}"}})
    cfg = {
        "model_list": entries,
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
        "litellm_settings": {"drop_params": True},
    }
    header = "# Generated by the e2eai wizard from e2eai.yaml. Change models with: uv run e2eai models\n"
    return header + yaml.safe_dump(cfg, sort_keys=False)


def read_env(path: Path) -> dict[str, str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    return dict(line.split("=", 1) for line in lines if "=" in line and not line.startswith("#"))


def load_answers(root: Path) -> dict:
    """Rebuild answers from an existing install, so `models` changes models without new passwords."""
    env = read_env(root / "deploy" / "compose" / ".env")
    cfg = yaml.safe_load((root / "e2eai.yaml").read_text(encoding="utf-8"))
    profiles = set(filter(None, env["COMPOSE_PROFILES"].split(",")))
    key_envs = {k for _, k in EXTERNAL_PROVIDERS.values()}
    return {
        "tier": cfg["tier"],
        "bind": env["BIND_ADDRESS"],
        "gpu": "compose.gpu.yaml" in env["COMPOSE_FILE"],
        "host_ollama": "host.docker.internal" in env["OLLAMA_BASE_URL"],
        "optional": {n: n in profiles for n in ("ollama", "tei-embed", "tei-rerank", "keycloak")},
        "tei_models": {"tei-embed": env["TEI_EMBED_MODEL"], "tei-rerank": env["TEI_RERANK_MODEL"]},
        "ports": {s.name: int(env[s.port_env]) for s in SERVICES},
        "users": {k: env[k] for k in USERS},
        "secrets": {k: env[k] for k in SECRETS},
        "models": cfg["models"],
        "api_keys": {k: v for k, v in env.items() if k in key_envs and v},
        "egress_external": cfg["egress"]["external_apis"],
    }


def _write_private(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    os.chmod(path, 0o600)  # owner-only on POSIX; best effort on Windows


def write_all(root: Path, a: dict, force: bool) -> list[Path]:
    compose = root / "deploy" / "compose"
    env = compose / ".env"
    if env.exists():
        if not force:
            raise FileExistsError(env)
        env.rename(compose / f".env.bak-{time.strftime('%Y%m%d-%H%M%S')}")
    images = yaml.safe_load((root / "deploy" / "versions.lock").read_text())["images"]
    _write_private(env, render_env(a, images))
    _write_private(compose / "seaweedfs" / "s3.json", render_s3_config(a))
    (root / "e2eai.yaml").write_text(render_config(a), encoding="utf-8", newline="\n")
    catalog = load_catalog(root) if (root / "catalog" / "models.yaml").exists() else {}
    litellm = compose / "litellm" / "config.yaml"
    litellm.parent.mkdir(parents=True, exist_ok=True)
    litellm.write_text(render_litellm_config(a, catalog), encoding="utf-8", newline="\n")
    return [env, compose / "seaweedfs" / "s3.json", root / "e2eai.yaml", litellm]
